/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stats;

import com.google.gson.Gson;
import stats.function.Avg;
import stats.function.Max;
import stats.function.StatFunc;
import stats.function.Values;

import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.util.HashMap;
import java.util.Map;

public class App {

    public static void main(String[] args) throws IOException {
        if (args.length != 2) {
            System.out.println("Wrong params. Please use " +
                    "\"java -jar app_name.jar <Function Name> testData.json\"");
            System.exit(1);
        }
        String functionName = args[0];
        String fileName = args[1];
        Reader reader = new FileReader(fileName);
        Gson gson = new Gson();
        DataItem[] data = gson.fromJson(reader, DataItem[].class);
        if (data.length == 0) {
            System.out.println("Input array length 0");
            System.exit(2);
        }
        Map<String, StatFunc<DataItem>> func = new HashMap<>();
        func.put("avg", new Avg<>(
                item -> item.ups_adv_battery_run_time_remaining,
                avg -> System.out.println(avg.result()))
        );
        func.put("max", new Max<>(
                item -> item.ups_adv_output_voltage,
                max -> System.out.println(max.result()))
        );
        func.put("values", new Values<>(
                item -> item.host,
                values -> System.out.println(gson.toJson(values.result())))
        );

        StatFunc<DataItem> statFunc = func.get(functionName);
        for (DataItem item : data) {
            statFunc.collect(item);
        }
        statFunc.print();
    }
}
