/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stats;

import com.google.gson.Gson;

import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.util.Set;

public class App {

    public static void main(String[] args) throws IOException {
        if (args.length != 2) {
            System.out.println("Wrong params. Please use " +
                    "\"java -jar app_name.jar <Function Name> testData.json\"");
            System.exit(1);
        }
        String functionName = args[0];
        String fileName = args[1];
        Reader reader = new FileReader(fileName);
        Gson gson = new Gson();
        DataItem[] data = gson.fromJson(reader, DataItem[].class);
        if (data.length == 0) {
            System.out.println("Input array length 0");
            System.exit(2);
        }
        Functions app = new Functions();
        if ("avg".equals(functionName)) {
            double result = app.avg(data);
            System.out.println(result);
        } else if ("max".equals(functionName)) {
            long result = app.max(data);
            System.out.println(result);
        } else if ("values".equals(functionName)) {
            Set<String> result = app.values(data);
            System.out.println(gson.toJson(result));
        }
    }
}
