/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stats;

import com.google.gson.Gson;
import org.junit.Before;
import org.junit.Test;

import java.io.*;
import java.net.URL;
import java.util.HashSet;
import java.util.Set;

import static org.junit.Assert.*;

public class AppTest {

    private DataItem[] data;

    @Before public void loadJson() throws IOException {
        Gson gson = new Gson();
        URL resource = AppTest.class.getClassLoader().getResource("testData.json");
        assert resource != null;
        Reader reader = new FileReader(resource.getFile());
        data = gson.fromJson(reader, DataItem[].class);
    }

    @Test public void appMaxTest() {
        assertEquals(new Functions().max(data), 241);
    }

    @Test public void appAvgTest() {
        assertEquals(new Functions().avg(data), 412712.827696618, 0);
    }

    @Test public void appValuesTest() {
        Set<String> hosts = new HashSet<>();
        hosts.add("192.168.10.8");
        hosts.add("192.168.11.9");
        assertEquals(new Functions().values(data), hosts);
    }
}
