/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stats;

import com.google.gson.Gson;
import org.junit.Before;
import org.junit.Test;
import stats.function.Avg;
import stats.function.Max;
import stats.function.StatFunc;
import stats.function.Values;

import java.io.*;
import java.net.URL;
import java.util.HashSet;
import java.util.Set;

import static org.junit.Assert.*;

public class AppTest {

    private DataItem[] data;

    private void apply(StatFunc<DataItem> func) {
        for (DataItem item : data) {
            func.collect(item);
        }
    }

    @Before public void loadJson() throws IOException {
        Gson gson = new Gson();
        URL resource = AppTest.class.getClassLoader().getResource("testData.json");
        assert resource != null;
        Reader reader = new FileReader(resource.getFile());
        data = gson.fromJson(reader, DataItem[].class);
    }

    @Test public void appMaxTest() {
        Max<DataItem> max = new Max<>(item -> item.ups_adv_output_voltage);
        apply(max);
        assertEquals(max.result(), 241);
    }

    @Test public void appAvgTest() {
        Avg<DataItem> avg = new Avg<>(item -> item.ups_adv_battery_run_time_remaining);
        apply(avg);
        assertEquals(avg.result(), 412712.827696618, 0);
    }

    @Test public void appValuesTest() {
        Set<String> hosts = new HashSet<>();
        hosts.add("192.168.10.8");
        hosts.add("192.168.11.9");
        Values<DataItem> values = new Values<>(item -> item.host);
        apply(values);
        assertEquals(values.result(), hosts);
    }
}
